using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using UnityEditor;
using UnityEditor.Build.Reporting;
using UnityEngine;
using UnityEngine.Networking;

public class Build
{
    [MenuItem("Build/Build All")]
    public static void BuildAllPlayers()
    {
        string path = EditorUtility.SaveFolderPanel("Choose Location of Built Game", "", "");
        if (string.IsNullOrEmpty(path)) return;


        string newGuid = Guid.NewGuid().ToString();

        string classContent = $@"
        // Auto-generated by BuildScript. Do not modify.
        namespace BuildSystem
        {{
            public static class BuildInfo
            {{
                public const string buildId = ""WIN{newGuid}"";
            }}
        }}";

        File.WriteAllText(Application.dataPath + "/BuildInfo.cs", classContent);
        var buildOptions = new BuildPlayerOptions()
        {
            scenes = new string[] { "Assets/Scenes/TerrainGenTest.unity", "Assets/Scenes/Credits.unity" },
            locationPathName = path + "/Windows/Smokejumpers.exe",
            target = BuildTarget.StandaloneWindows64,
        };
        var buildReport = BuildPipeline.BuildPlayer(buildOptions);


        if (buildReport.summary.result != BuildResult.Succeeded)
        {
            UnityEngine.Debug.Log("Windows build failed!\n\n" + buildReport.SummarizeErrors());
            return;
        }
        classContent = $@"
        // Auto-generated by BuildScript. Do not modify.
        namespace BuildSystem
        {{
            public static class BuildInfo
            {{
                public const string buildId = ""LNX{newGuid}"";
            }}
        }}";

        File.WriteAllText(Application.dataPath + "/BuildInfo.cs", classContent);
        buildOptions = new BuildPlayerOptions()
        {
            scenes = new string[] { "Assets/Scenes/TerrainGenTest.unity", "Assets/Scenes/Credits.unity" },
            locationPathName = path + "/Linux/Smokejumpers.x86_64",
            target = BuildTarget.StandaloneLinux64,
        };
        buildReport = BuildPipeline.BuildPlayer(buildOptions);


        if (buildReport.summary.result != BuildResult.Succeeded)
        {
            UnityEngine.Debug.Log("Linux build failed!\n\n" + buildReport.SummarizeErrors());
            return;
        }

        classContent = $@"
        // Auto-generated by BuildScript. Do not modify.
        namespace BuildSystem
        {{
            public static class BuildInfo
            {{
                public const string buildId = ""OSX{newGuid}"";
            }}
        }}";

        File.WriteAllText(Application.dataPath + "/BuildInfo.cs", classContent);
        buildOptions = new BuildPlayerOptions()
        {
            scenes = new string[] { "Assets/Scenes/TerrainGenTest.unity", "Assets/Scenes/Credits.unity" },
            locationPathName = path + "/OSX/Smokejumpers.app",
            target = BuildTarget.StandaloneOSX,
        };
        buildReport = BuildPipeline.BuildPlayer(buildOptions);


        if (buildReport.summary.result != BuildResult.Succeeded)
        {
            UnityEngine.Debug.Log("OSX build failed!\n\n" + buildReport.SummarizeErrors());
            return;
        }

        classContent = $@"
        // Auto-generated by BuildScript. Do not modify.
        namespace BuildSystem
        {{
            public static class BuildInfo
            {{
                public const string buildId = ""{newGuid}"";
            }}
        }}";
        File.WriteAllText(Application.dataPath + "/BuildInfo.cs", classContent);
    }
    [MenuItem("Build/Publish All")]
    public static void PublishAllBuilds()
    {
        string scriptPath = "/mnt/c/Users/ffkoe/OneDrive/Documents/Scripts/SmokejumpersBuildCompresser.sh";

        UnityEngine.Debug.Log($"Attempting to run WSL script at: {scriptPath}");
        ProcessStartInfo startInfo = new ProcessStartInfo();
        startInfo.FileName = "wsl.exe";
        startInfo.Arguments = $"'{scriptPath}' -r {Application.version} -y";
        startInfo.RedirectStandardOutput = true;
        startInfo.RedirectStandardError = true;
        startInfo.UseShellExecute = false;
        startInfo.CreateNoWindow = true;
        using (Process process = Process.Start(startInfo))
        {
            string output = process.StandardOutput.ReadToEnd();
            string error = process.StandardError.ReadToEnd();

            process.WaitForExit();

            if (!string.IsNullOrEmpty(output))
            {
                UnityEngine.Debug.Log($"WSL Output:\n{output}");
            }

            if (!string.IsNullOrEmpty(error))
            {
                UnityEngine.Debug.LogError($"WSL Error:\n{error}");
            }
        }
    }
}