
        // Auto-generated by BuildScript. Do not modify.
        namespace BuildSystem
        {
            public static class BuildInfo
            {
                public const string buildId = "4e58fbd7-adcf-4ad6-9d89-48ee284eb4d6";
            }
        }